name: smart_staffs_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  path_provider: ^2.1.4
  path: ^1.9.0
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  camera: ^0.11.0+2

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: vegan
      fonts:
        - asset: assets/fonts/Vegan.ttf

