name: smart_admin_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  flutter_spinkit: ^5.2.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: vegan
      fonts:
        - asset: assets/fonts/Vegan.ttf

